In [139]:
import numpy as np
test = """F10
N3
F7
R90
F11"""
test = [t for t in test.split("\n")]

In [140]:
with open("input.txt", "r") as f:
    data = [t.strip() for t in f]
data

['S1',
 'R270',
 'S5',
 'W2',
 'F63',
 'S3',
 'L90',
 'W4',
 'F59',
 'S1',
 'F21',
 'W4',
 'R90',
 'W1',
 'R180',
 'S2',
 'W2',
 'F91',
 'W5',
 'R270',
 'F97',
 'R90',
 'E2',
 'R90',
 'F6',
 'W1',
 'R90',
 'W3',
 'F1',
 'S4',
 'F1',
 'N3',
 'F76',
 'S4',
 'W5',
 'F88',
 'W4',
 'N3',
 'W2',
 'F48',
 'N1',
 'F50',
 'E3',
 'F18',
 'L90',
 'F30',
 'S3',
 'R90',
 'W1',
 'N5',
 'W1',
 'R90',
 'R90',
 'E1',
 'S2',
 'F73',
 'R90',
 'S4',
 'F89',
 'F34',
 'L90',
 'F11',
 'S3',
 'F20',
 'S5',
 'E3',
 'R180',
 'E3',
 'L90',
 'E2',
 'F1',
 'E3',
 'N3',
 'F84',
 'R90',
 'E4',
 'R180',
 'F24',
 'N3',
 'L90',
 'F15',
 'W4',
 'F52',
 'S5',
 'L180',
 'N4',
 'R90',
 'E5',
 'F11',
 'S4',
 'F27',
 'R180',
 'E4',
 'R180',
 'W3',
 'N2',
 'W1',
 'S3',
 'W4',
 'E5',
 'F97',
 'L180',
 'E3',
 'N4',
 'E3',
 'S4',
 'L90',
 'S4',
 'R90',
 'N5',
 'E1',
 'S5',
 'F19',
 'E1',
 'S2',
 'L180',
 'F36',
 'S2',
 'L90',
 'W1',
 'F8',
 'W1',
 'F67',
 'E3',
 'L90',
 'F33',
 'N4',
 'F35',
 'W2',
 'F33',
 'L180',
 'N1',
 'L90'

In [141]:
coord = {"N": np.array([0, 1]),
             "S": np.array([0, -1]),
             "E": np.array([1, 0]),
             "W": np.array([-1, 0])}

turn = {"L": -1},
        "R":  1}}

move =  {0:"N",
              90:"E",
              180:"S",
              270:"W"}

IndentationError: unexpected indent (<ipython-input-141-8bb1b3c3e532>, line 7)

In [142]:
start = [0,0]
current = start[:]
face = 90
for i in data:
    inst, val = i[0], int(i[1:])
    if inst == "F":
        direction = move[face]
        current += val * coord[direction]
    if inst in turn.keys():
        face += val * turn[inst]
        face = face % 360
    if inst in coord.keys():
        current += val * coord[inst]
    
sum(abs(current))

1319

In [143]:
start = np.array([0,0])
way_point = np.array([10,1])
current = start[:]
for i in data:
    inst, val = i[0], int(i[1:])
    if inst == "F":
        current += val * way_point
    if inst in ["R", "L"]:
        if i in ["R90", "L270"]:
            way_point = np.array(list(map(operator.mul,[1,-1],way_test[::-1])))
        if val == 180:
            way_point =  -1 * way_point
        if i in ["R270", "L90"]:
            way_point = np.array(list(map(operator.mul,[-1,1],way_test[::-1])))
    if inst in coord.keys():
        way_point += val * coord[inst]

sum(abs(current))

12209

In [75]:
import operator
list(map(operator.add,start,way_point))

[10, 1]

True

In [120]:
way_point = np.array(list(map(operator.mul,[-1,1],way_test[::-1]

array([-4, 10])

In [118]:
way_test = np.array([10,4])

In [136]:
current = start[:]
start = np.array([10,-10])


In [137]:
way_point = np.array([10,1])
start += way_point * 10
start

array([110,   0])

In [103]:
-1 * way_point

array([-10,  -1])

In [134]:
start[10,-10]

array([0, 0])